# Generated by Django 5.1.6 on 2026-09-15 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_serviceorder_actual_end_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Электронная почта'), ('messenger', 'Мессенджер'), ('portal', 'Портал')], max_length=16)),
                ('subject_ru', models.CharField(max_length=255)),
                ('subject_en', models.CharField(max_length=255)),
                ('body_ru', models.TextField()),
                ('body_en', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('channel', models.CharField(choices=[('email', 'Электронная почта'), ('messenger', 'Мессенджер'), ('portal', 'Портал')], default='email', max_length=16)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('recognized', models.BooleanField(db_index=True, default=False)),
                ('suggested_action', models.CharField(blank=True, max_length=32)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_inbox_messages', to=settings.AUTH_USER_MODEL)),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='orders.serviceorder')),
            ],
            options={
                'verbose_name': 'Входящее сообщение',
                'verbose_name_plural': 'Входящие',
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('channel', models.CharField(choices=[('email', 'Электронная почта'), ('messenger', 'Мессенджер'), ('portal', 'Портал')], db_index=True, max_length=16)),
                ('channel_mode', models.CharField(blank=True, max_length=8)),
                ('to', models.JSONField(default=list)),
                ('template_code', models.CharField(blank=True, max_length=48)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('related_entity_type', models.CharField(blank=True, max_length=24)),
                ('related_entity_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('eml_key', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name': 'Исходящее сообщение',
                'verbose_name_plural': 'Исходящие',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(condition=models.Q(('status', 'queued')), fields=['next_attempt_at'], name='outbox_due_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('kind', models.CharField(choices=[('flight_status', 'Смена статуса рейса'), ('service_confirmed', 'Заявка подтверждена'), ('service_rejected', 'Заявка отклонена'), ('deadline', 'Приближение срока'), ('sla_breach', 'Нарушение SLA'), ('contract_expiry', 'Истечение контракта'), ('payment_overdue', 'Просрочка оплаты'), ('low_margin', 'Низкая маржа')], db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('info', 'Сведение'), ('warning', 'Предупреждение'), ('critical', 'Критично')], default='info', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(condition=models.Q(('read_at__isnull', True)), fields=['user', '-created_at'], name='notification_unread_idx')],
            },
        ),
    ]
