"""Второй фактор и связь портального пользователя с контрагентом.

Ограничения в базе (`client_user_has_client`, `vendor_user_has_vendor`)
не дают завести пользователя роли «Клиент» или «Поставщик» без контрагента:
такому пользователю фильтр выборки нечем ограничить, и он увидел бы всё
(`BACKEND.md § 3.7`).
"""

# Generated by Django 5.1.6 on 2026-09-13 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(editable=False, max_length=128)),
                ('created_at', models.DateTimeField(editable=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Резервный код',
                'verbose_name_plural': 'Резервные коды',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(editable=False)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Момент подтверждения кодом из приложения', null=True)),
            ],
            options={
                'verbose_name': 'Второй фактор',
                'verbose_name_plural': 'Вторые факторы',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Обязателен для роли «Клиент»', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='counterparties.client'),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Обязателен для роли «Поставщик»', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='counterparties.vendor'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'client'), _negated=True), ('client__isnull', False), _connector='OR'), name='client_user_has_client'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'vendor'), _negated=True), ('vendor__isnull', False), _connector='OR'), name='vendor_user_has_vendor'),
        ),
        migrations.AddField(
            model_name='backupcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twofactordevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='backupcode',
            index=models.Index(fields=['user', 'used_at'], name='accounts_ba_user_id_019926_idx'),
        ),
    ]
