# Generated by Django 5.1.6 on 2026-09-24 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_two_factor_and_tenant_links'),
        ('counterparties', '0004_vendorservicemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('kind', models.CharField(choices=[('client', 'Клиент'), ('vendor', 'Поставщик')], db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('email_pending', 'Ожидает подтверждения почты'), ('pending', 'На согласовании'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='email_pending', max_length=16)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('password_hash', models.CharField(editable=False, max_length=128)),
                ('company_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('tax_id', models.CharField(blank=True, help_text='ИНН или аналог', max_length=32)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('specializations', models.JSONField(blank=True, default=list, help_text='Категории услуг по ТЗ 3.2.1')),
                ('coverage_airports', models.JSONField(blank=True, default=list, help_text='Коды ИКАО, где поставщик работает')),
                ('comment', models.TextField(blank=True)),
                ('email_token_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('email_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='counterparties.client')),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to=settings.AUTH_USER_MODEL)),
                ('created_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='counterparties.vendor')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_registrations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрацию',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('email_pending', 'pending'))), fields=('email',), name='one_open_registration_per_email'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('approved', 'rejected')), _negated=True), ('decided_at__isnull', False), _connector='OR'), name='registration_decision_has_date', violation_error_message='Решение по заявке обязано нести дату.')],
            },
        ),
    ]
