# Generated by Django 5.1.6 on 2026-09-13 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('icao_type', models.CharField(db_index=True, max_length=4, unique=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('light', 'Лёгкий'), ('midsize', 'Средний'), ('heavy', 'Тяжёлый'), ('airliner', 'Магистральный'), ('cargo', 'Грузовой')], max_length=16)),
                ('seats', models.PositiveSmallIntegerField(default=0)),
                ('cruise_speed_kts', models.PositiveSmallIntegerField(help_text='Крейсерская скорость, узлы. Оценка времени в пути — DOMAIN.md § 7.8')),
                ('fuel_burn_kg_per_hour', models.PositiveIntegerField(default=0)),
                ('turnaround_min', models.PositiveSmallIntegerField(default=60, help_text='Минимальный интервал между рейсами борта, поиск конфликтов')),
            ],
            options={
                'verbose_name': 'Тип воздушного судна',
                'verbose_name_plural': 'Типы воздушных судов',
                'ordering': ('icao_type',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('category', models.CharField(choices=[('fuel', 'Топливообеспечение'), ('handling', 'Наземное обслуживание'), ('catering', 'Кейтеринг'), ('transport', 'Транспорт'), ('permits', 'Разрешительные документы'), ('deicing', 'Противообледенительная обработка')], db_index=True, max_length=16)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('L', 'литр'), ('kg', 'килограмм'), ('ea', 'штука'), ('hour', 'час'), ('pax', 'пассажир'), ('flight', 'рейс')], max_length=8)),
                ('requires_weather', models.BooleanField(default=False, help_text='При заказе подтягивается METAR/TAF, ADR-029')),
                ('lead_time_h', models.PositiveSmallIntegerField(default=0, help_text='Минимальный срок подачи заявки, часы. Проверка мягкая')),
                ('requires_act_to_complete', models.BooleanField(default=False, help_text='Заявка не закрывается без приложенного акта')),
                ('required_attributes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Каталог услуг',
                'ordering': ('category', 'code'),
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('percent', models.DecimalField(decimal_places=4, max_digits=6)),
                ('applicability', models.CharField(choices=[('domestic', 'Внутри РФ'), ('international', 'Международная перевозка'), ('export_of_services', 'Место реализации вне РФ'), ('exempt', 'Освобождено от НДС')], max_length=24)),
                ('legal_basis', models.CharField(blank=True, help_text='Норма НК РФ', max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ставка НДС',
                'verbose_name_plural': 'Ставки НДС',
                'ordering': ('-percent', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('icao', models.CharField(db_index=True, max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('iata', models.CharField(blank=True, db_index=True, max_length=3)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('city_ru', models.CharField(blank=True, max_length=255)),
                ('city_en', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('timezone', models.CharField(help_text='Зона IANA, например Europe/Moscow', max_length=64)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('elevation_ft', models.IntegerField(default=0)),
                ('is_coordinated', models.BooleanField(default=False, help_text='Аэропорт слот-координируется, IATA Level 3')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
                'ordering': ('icao',),
                'indexes': [models.Index(fields=['country'], name='catalog_air_country_42bf7b_idx')],
            },
        ),
    ]
