# Generated by Django 5.1.6 on 2026-09-14 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPrice',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('airport_icao', models.CharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('min_charge_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(db_index=True)),
                ('surcharges', models.JSONField(blank=True, default=list)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='counterparties.vendor')),
            ],
            options={
                'verbose_name': 'Цена поставщика',
                'verbose_name_plural': 'Цены поставщиков',
                'ordering': ('airport_icao', 'service', '-valid_from'),
                'indexes': [models.Index(fields=['vendor', 'service', 'airport_icao', 'valid_from'], name='vendorprice_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__gt', models.F('valid_from'))), name='vendorprice_valid_to_after_valid_from', violation_error_message='Дата окончания цены раньше даты начала'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='vendorprice_amount_not_negative', violation_error_message='Отрицательная закупочная цена не имеет смысла')],
            },
        ),
    ]
