# Generated by Django 5.1.6 on 2026-09-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('schedule', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=8)),
                ('time_utc', models.CharField(default='06:00', max_length=5)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'XLSX'), ('csv', 'CSV'), ('xml', 'XML')], default='xlsx', max_length=8)),
                ('recipients', models.JSONField(default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Подписка на отчёт',
                'verbose_name_plural': 'Подписки на отчёты',
                'ordering': ('code', 'schedule'),
            },
        ),
    ]
