# Generated by Django 5.1.6 on 2026-09-13 21:38

import django.core.validators
import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('counterparties', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('leg', models.CharField(choices=[('departure', 'Вылет'), ('arrival', 'Прилёт')], max_length=16)),
                ('airport_icao', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('status', django_fsm.FSMField(choices=[('draft', 'Черновик'), ('ordered', 'Заказана'), ('confirmed', 'Подтверждена'), ('in_progress', 'Выполняется'), ('completed', 'Выполнена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], db_index=True, default='draft', max_length=16, protected=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='flights.flight')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.service')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='counterparties.vendor')),
            ],
            options={
                'verbose_name': 'Заявка на услугу',
                'verbose_name_plural': 'Заявки на услуги',
                'ordering': ('flight', 'leg', 'created_at'),
                'indexes': [models.Index(fields=['flight'], name='orders_serv_flight__e81a96_idx'), models.Index(fields=['vendor', 'status'], name='orders_serv_vendor__b8d201_idx')],
            },
        ),
    ]
