# Generated by Django 5.1.6 on 2026-09-14 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vendorprice'),
        ('counterparties', '0003_vendor_exchange_method_and_more'),
        ('flights', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='actual_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='actual_purchase_unit_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='actual_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='actual_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='counterparties.vendorcontract'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='contract_terms_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='purchase_cost_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='purchase_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='purchase_min_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='purchase_surcharges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='purchase_unit_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='replaced_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='orders.serviceorder'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='sla_breached',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='sla_confirm_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(condition=models.Q(('status', 'ordered')), fields=['sla_confirm_deadline'], name='order_sla_pending_idx'),
        ),
    ]
