# Generated by Django 5.1.6 on 2026-09-14 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0002_vendorprice'),
        ('counterparties', '0003_vendor_exchange_method_and_more'),
        ('flights', '0001_initial'),
        ('orders', '0002_serviceorder_actual_end_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=16)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Счётчик номеров документов',
                'verbose_name_plural': 'Счётчики номеров документов',
                'constraints': [models.UniqueConstraint(fields=('doc_type', 'year'), name='unique_document_counter')],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('fx_snapshot', models.JSONField(blank=True, default=dict)),
                ('subtotal_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fees_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fees', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выставлена'), ('accepted', 'Принята'), ('declined', 'Отклонена'), ('expired', 'Истекла'), ('voided', 'Аннулирована')], db_index=True, default='draft', max_length=16)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='counterparties.client')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='flights.flight')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voids', to='billing.quote')),
            ],
            options={
                'verbose_name': 'Котировка',
                'verbose_name_plural': 'Котировки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('fx_snapshot', models.JSONField(blank=True, default=dict)),
                ('subtotal_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fees_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fees', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выставлен'), ('sent', 'Отправлен'), ('partially_paid', 'Оплачен частично'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('voided', 'Аннулирован')], db_index=True, default='draft', max_length=16)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('plan_fact_comparison', models.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='counterparties.client')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='flights.flight')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voids', to='billing.invoice')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.quote')),
            ],
            options={
                'verbose_name': 'Счёт клиенту',
                'verbose_name_plural': 'Счета клиентам',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TariffRule',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('category', models.CharField(blank=True, help_text='Правило на категорию: приоритет 2', max_length=16)),
                ('airport_icao', models.CharField(blank=True, help_text='Модификатор: +1 к приоритету', max_length=4)),
                ('mode', models.CharField(choices=[('cost_plus', 'Закупка плюс наценка'), ('fixed', 'Фиксированная цена'), ('pass_through', 'По себестоимости')], max_length=16)),
                ('markup_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('fixed_currency', models.CharField(blank=True, max_length=3)),
                ('discount_kind', models.CharField(blank=True, choices=[('percent', 'Процент'), ('fixed', 'Фиксированная')], max_length=8)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='counterparties.client')),
                ('service', models.ForeignKey(blank=True, help_text='Правило на конкретную услугу: приоритет 3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rules', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Тарифное правило',
                'verbose_name_plural': 'Тарифные правила',
                'ordering': ('client', '-valid_from'),
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('description', models.CharField(max_length=500)),
                ('airport_icao', models.CharField(max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('vat_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='orders.serviceorder')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='catalog.vatrate')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.quote')),
                ('tariff_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='billing.tariffrule')),
            ],
            options={
                'verbose_name': 'Строка документа',
                'verbose_name_plural': 'Строки документов',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(models.Q(('number', ''), _negated=True), ('issued_at__isnull', False)), _connector='OR'), name='quote_issued_has_number_and_date', violation_error_message='У выставленной котировки обязаны быть номер и дата выставления'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('number',), name='quote_number_unique'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status', 'due_date'], name='billing_inv_client__d97c5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(models.Q(('number', ''), _negated=True), ('issued_at__isnull', False)), _connector='OR'), name='invoice_issued_has_number_and_date', violation_error_message='У выставленного счёта обязаны быть номер и дата выставления'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('number',), name='invoice_number_unique'),
        ),
        migrations.AddIndex(
            model_name='tariffrule',
            index=models.Index(fields=['client', 'valid_from', 'valid_to'], name='billing_tar_client__f5a8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffrule',
            index=models.Index(fields=['client', 'service'], name='billing_tar_client__014c04_idx'),
        ),
        migrations.AddConstraint(
            model_name='tariffrule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gt', models.F('valid_from'))), name='tariff_valid_to_after_valid_from', violation_error_message='Дата окончания правила раньше даты начала'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invoice__isnull', True), ('quote__isnull', False)), models.Q(('invoice__isnull', False), ('quote__isnull', True)), _connector='OR'), name='document_line_has_exactly_one_owner', violation_error_message='Строка принадлежит либо котировке, либо счёту, но не обоим'),
        ),
    ]
