# Generated by Django 5.1.6 on 2026-09-17 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_documentcounter_quote_invoice_tariffrule_and_more'),
        ('catalog', '0002_vendorprice'),
        ('counterparties', '0003_vendor_exchange_method_and_more'),
        ('orders', '0002_serviceorder_actual_end_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('number', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('reconciliation', models.JSONField(blank=True, default=dict)),
                ('unmapped_codes', models.JSONField(blank=True, default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='counterparties.vendor')),
            ],
            options={
                'verbose_name': 'Счёт поставщика',
                'verbose_name_plural': 'Счета поставщиков',
                'ordering': ('-issued_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('due_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает согласования'), ('approved', 'Согласована'), ('scheduled', 'В плане платежей'), ('paid', 'Оплачена'), ('disputed', 'Спорная'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payables', to=settings.AUTH_USER_MODEL)),
                ('service_orders', models.ManyToManyField(blank=True, related_name='payables', to='orders.serviceorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='counterparties.vendor')),
                ('vendor_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='billing.vendorinvoice')),
            ],
            options={
                'verbose_name': 'Заявка на оплату',
                'verbose_name_plural': 'Заявки на оплату',
                'ordering': ('due_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='VendorInvoiceLine',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('position', models.PositiveSmallIntegerField(help_text='Номер строки в счёте: на него ссылается расхождение')),
                ('airport_icao', models.CharField(max_length=4)),
                ('service_date', models.DateTimeField()),
                ('service_code', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.vendorinvoice')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_invoice_lines', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Строка счёта поставщика',
                'verbose_name_plural': 'Строки счетов поставщиков',
                'ordering': ('invoice', 'position'),
            },
        ),
        migrations.AddConstraint(
            model_name='vendorinvoice',
            constraint=models.UniqueConstraint(fields=('vendor', 'number'), name='unique_vendor_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payable_amount_not_negative', violation_error_message='Сумма заявки на оплату не может быть отрицательной'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'pending'), ('status', 'cancelled'), ('approved_at__isnull', False), _connector='OR'), name='payable_approved_has_date', violation_error_message='Заявка после согласования обязана нести дату согласования'),
        ),
        migrations.AddConstraint(
            model_name='vendorinvoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'position'), name='unique_vendor_invoice_line_position'),
        ),
    ]
