# Generated by Django 5.1.6 on 2026-09-17 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_vendorinvoice_payable_vendorinvoiceline_and_more'),
        ('counterparties', '0004_vendorservicemapping'),
        ('orders', '0002_serviceorder_actual_end_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payable',
            name='payable_approved_has_date',
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'scheduled', 'paid']), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='payable_approved_has_date', violation_error_message='Согласованная заявка обязана нести дату согласования'),
        ),
    ]
