# Generated by Django 5.1.6 on 2026-09-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('code', models.CharField(db_index=True, help_text='FX, WX, SMTP, …', max_length=16)),
                ('mode', models.CharField(choices=[('live', 'Боевой режим'), ('stub', 'Заглушка')], help_text='Фактический режим на момент вызова', max_length=8)),
                ('operation', models.CharField(help_text='rates_on_date, send, …', max_length=64)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('error', 'Ошибка'), ('timeout', 'Таймаут')], db_index=True, max_length=8)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('response_bytes', models.PositiveIntegerField(default=0)),
                ('request_body', models.TextField(blank=True)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=32)),
                ('related_entity_id', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Обмен с внешней системой',
                'verbose_name_plural': 'Журнал обменов',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['code', '-created_at'], name='integration_code_a74545_idx'), models.Index(fields=['status', '-created_at'], name='integration_status_eab5ae_idx')],
            },
        ),
    ]
