# Generated by Django 5.1.6 on 2026-09-13 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('registration', models.CharField(db_index=True, help_text='Бортовой номер, RA-67231', max_length=16, unique=True)),
                ('status', models.CharField(choices=[('serviceable', 'Исправен'), ('maintenance', 'На техобслуживании'), ('aog', 'AOG, неисправен на земле')], db_index=True, default='serviceable', max_length=16)),
                ('home_base_icao', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(blank=True, help_text='Клиент-оператор, если борт клиента', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='counterparties.client')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='catalog.aircrafttype')),
            ],
            options={
                'verbose_name': 'Воздушное судно',
                'verbose_name_plural': 'Воздушные суда',
                'ordering': ('registration',),
            },
        ),
        migrations.CreateModel(
            name='AircraftApproval',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('kind', models.CharField(choices=[('ETOPS', 'ETOPS'), ('RVSM', 'RVSM'), ('MNPS', 'MNPS'), ('CAT_II', 'CAT II'), ('CAT_III', 'CAT III'), ('RNP', 'RNP'), ('other', 'Иной')], max_length=16)),
                ('number', models.CharField(blank=True, max_length=64)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='fleet.aircraft')),
            ],
            options={
                'verbose_name': 'Допуск борта',
                'verbose_name_plural': 'Допуски борта',
                'ordering': ('aircraft', 'kind'),
                'constraints': [models.UniqueConstraint(fields=('aircraft', 'kind', 'valid_from'), name='unique_aircraft_approval_period')],
            },
        ),
    ]
