# Generated by Django 5.1.6 on 2026-09-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('settlement_currency', models.CharField(default='RUB', max_length=3)),
                ('default_locale', models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('settlement_currency', models.CharField(default='RUB', max_length=3)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ('name',),
            },
        ),
    ]
