# Generated by Django 5.1.6 on 2026-09-14 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_two_factor_and_tenant_links'),
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('locale', models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=2)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ('-is_primary', 'name'),
            },
        ),
        migrations.CreateModel(
            name='VendorCertificate',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('kind', models.CharField(choices=[('IATA', 'IATA'), ('ADR', 'ADR'), ('ISO', 'ISO'), ('other', 'Прочий')], max_length=8)),
                ('number', models.CharField(max_length=64)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Сертификат поставщика',
                'verbose_name_plural': 'Сертификаты поставщиков',
                'ordering': ('valid_to',),
            },
        ),
        migrations.CreateModel(
            name='VendorContract',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('payment_mode', models.CharField(choices=[('prepayment', 'Предоплата'), ('postpayment', 'Постоплата'), ('deferred', 'Отсрочка')], default='deferred', max_length=16)),
                ('payment_defer_days', models.PositiveSmallIntegerField(default=0, help_text='0 для предоплаты и постоплаты')),
                ('payment_prepayment_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Доля предоплаты в процентах, только для mode=prepayment', max_digits=6, null=True)),
                ('number', models.CharField(max_length=64)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(db_index=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
            ],
            options={
                'verbose_name': 'Договор с поставщиком',
                'verbose_name_plural': 'Договоры с поставщиками',
                'ordering': ('valid_to',),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='credit_limit_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_limit_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_defer_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 для предоплаты и постоплаты'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_mode',
            field=models.CharField(choices=[('prepayment', 'Предоплата'), ('postpayment', 'Постоплата'), ('deferred', 'Отсрочка')], default='deferred', max_length=16),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_prepayment_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Доля предоплаты в процентах, только для mode=prepayment', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='coverage_airports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='coverage_regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='manual_quality_score',
            field=models.DecimalField(decimal_places=2, default='3.00', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_defer_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 для предоплаты и постоплаты'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_mode',
            field=models.CharField(choices=[('prepayment', 'Предоплата'), ('postpayment', 'Постоплата'), ('deferred', 'Отсрочка')], default='deferred', max_length=16),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_prepayment_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Доля предоплаты в процентах, только для mode=prepayment', max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit_amount__isnull', True), models.Q(('credit_limit_currency', ''), _negated=True), _connector='OR'), name='client_credit_limit_has_currency', violation_error_message='У кредитного лимита обязана быть валюта'),
        ),
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='counterparties.client'),
        ),
        migrations.AddField(
            model_name='contact',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='counterparties.vendor'),
        ),
        migrations.AddField(
            model_name='vendorcertificate',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='counterparties.vendor'),
        ),
        migrations.AddField(
            model_name='vendorcontract',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='counterparties.vendor'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', False), ('vendor__isnull', True)), models.Q(('client__isnull', True), ('vendor__isnull', False)), _connector='OR'), name='contact_has_exactly_one_owner', violation_error_message='Контакт принадлежит либо клиенту, либо поставщику, но не обоим'),
        ),
        migrations.AddIndex(
            model_name='vendorcontract',
            index=models.Index(fields=['vendor', 'valid_to'], name='counterpart_vendor__08f26c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorcontract',
            constraint=models.UniqueConstraint(fields=('vendor', 'number'), name='contract_number_unique_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendorcontract',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gt', models.F('valid_from'))), name='contract_valid_to_after_valid_from', violation_error_message='Дата окончания договора раньше даты начала'),
        ),
    ]
