# Generated by Django 5.1.6 on 2026-09-14 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_contact_vendorcertificate_vendorcontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='exchange_method',
            field=models.CharField(choices=[('portal', 'Портал'), ('email', 'Почта'), ('api', 'API')], default='email', max_length=8),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='manual_quality_score',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
