# Generated by Django 5.1.6 on 2026-09-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vendorprice'),
        ('counterparties', '0003_vendor_exchange_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorServiceMapping',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('vendor_code', models.CharField(max_length=64)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_mappings', to='catalog.service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='counterparties.vendor')),
            ],
            options={
                'verbose_name': 'Соответствие номенклатуры',
                'verbose_name_plural': 'Соответствия номенклатуры',
                'ordering': ('vendor', 'vendor_code'),
                'constraints': [models.UniqueConstraint(fields=('vendor', 'vendor_code'), name='unique_vendor_service_code', violation_error_message='Для этого кода поставщика соответствие уже заведено')],
            },
        ),
    ]
