# Generated by Django 5.1.6 on 2026-09-13 21:38

import django.core.validators
import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_two_factor_and_tenant_links'),
        ('catalog', '0001_initial'),
        ('counterparties', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('type', models.CharField(choices=[('charter', 'Чартер'), ('ferry', 'Перегон'), ('ambulance', 'Санитарный'), ('cargo', 'Грузовой'), ('technical', 'Технический')], default='charter', max_length=16)),
                ('dep_icao', models.CharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('arr_icao', models.CharField(db_index=True, max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('std_utc', models.DateTimeField(db_index=True, help_text='Плановое время вылета')),
                ('sta_utc', models.DateTimeField(help_text='Плановое время прилёта')),
                ('atd_utc', models.DateTimeField(blank=True, help_text='Фактический вылет', null=True)),
                ('ata_utc', models.DateTimeField(blank=True, help_text='Фактический прилёт', null=True)),
                ('status', django_fsm.FSMField(choices=[('planned', 'Запланирован'), ('in_work', 'В работе'), ('ready_for_departure', 'Готов к вылету'), ('in_flight', 'В полёте'), ('arrived', 'Прилетел'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('aog', 'AOG / задержка')], db_index=True, default='planned', max_length=24, protected=True)),
                ('status_reason_code', models.CharField(blank=True, max_length=32)),
                ('status_reason_comment', models.TextField(blank=True)),
                ('pax_count', models.PositiveSmallIntegerField(default=0)),
                ('distance_nm', models.PositiveIntegerField(default=0)),
                ('block_time_min', models.PositiveIntegerField(default=0)),
                ('fuel_plan_kg', models.PositiveIntegerField(default=0)),
                ('billing_currency', models.CharField(default='RUB', help_text='Из клиента, фиксируется при создании', max_length=3)),
                ('fx_snapshot', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(blank=True, help_text='Может быть не назначен на момент планирования', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='fleet.aircraft')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='counterparties.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ('std_utc',),
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('PIC', 'Командир воздушного судна'), ('SIC', 'Второй пилот'), ('FA', 'Бортпроводник'), ('engineer', 'Бортинженер')], max_length=16)),
                ('license_no', models.CharField(blank=True, max_length=64)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Член экипажа',
                'verbose_name_plural': 'Экипаж',
                'ordering': ('flight', 'role'),
            },
        ),
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('dep_icao', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('arr_icao', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('requested_std_utc', models.DateTimeField()),
                ('pax_count', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests', to='counterparties.client')),
                ('flight', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='flights.flight')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Заявка на рейс',
                'verbose_name_plural': 'Заявки на рейс',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FlightTemplate',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('dep_icao', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('arr_icao', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('dep_time_local', models.TimeField(help_text='Местное время аэропорта вылета')),
                ('weekdays', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_templates', to='catalog.aircrafttype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_templates', to='counterparties.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_templates', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Шаблон рейса',
                'verbose_name_plural': 'Шаблоны рейсов',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='flights.flighttemplate'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('airport_icao', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Код ИКАО — четыре заглавные латинские буквы')])),
                ('type', models.CharField(choices=[('arrival', 'Прилёт'), ('departure', 'Вылет')], max_length=16)),
                ('requested_utc', models.DateTimeField()),
                ('confirmed_utc', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Запрошен'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён'), ('cancelled', 'Отменён')], db_index=True, default='requested', max_length=16)),
                ('message_number', models.CharField(blank=True, max_length=64)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
                'ordering': ('requested_utc',),
            },
        ),
        migrations.CreateModel(
            name='TemplateService',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('leg', models.CharField(choices=[('departure', 'Вылет'), ('arrival', 'Прилёт')], max_length=16)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.service')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_services', to='flights.flighttemplate')),
            ],
            options={
                'verbose_name': 'Услуга шаблона',
                'verbose_name_plural': 'Услуги шаблона',
                'ordering': ('template', 'leg'),
            },
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['status', 'std_utc'], name='flights_fli_status_034c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['client', 'std_utc'], name='flights_fli_client__cdab49_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['aircraft', 'std_utc'], name='flights_fli_aircraf_ff1c13_idx'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('flight', 'airport_icao', 'type'), name='unique_slot_per_flight_leg'),
        ),
    ]
