# Generated by Django 5.1.6 on 2026-09-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
