# Generated by Django 5.1.6 on 2026-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True)),
                ('clock_shifted', models.BooleanField(default=False, help_text='Действие совершено при сдвинутом модельном времени')),
                ('actor_id', models.CharField(db_index=True, max_length=40)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_role', models.CharField(choices=[('admin', 'Администратор'), ('dispatcher', 'Диспетчер'), ('sales', 'Продажи'), ('finance', 'Финансист'), ('manager', 'Руководитель'), ('client', 'Клиент'), ('vendor', 'Поставщик')], max_length=16)),
                ('source', models.CharField(choices=[('user', 'Действие пользователя'), ('system', 'Автоматический переход'), ('seed', 'Демонстрационный генератор')], default='user', max_length=8)),
                ('entity_type', models.CharField(choices=[('flight', 'Рейс'), ('service_order', 'Заявка на услугу'), ('vendor', 'Поставщик'), ('client', 'Клиент'), ('contract', 'Контракт'), ('tariff', 'Тариф'), ('quote', 'Котировка'), ('invoice', 'Счёт'), ('payable', 'Заявка на оплату'), ('payment', 'Платёж'), ('reconciliation', 'Сверка'), ('user', 'Пользователь'), ('settings', 'Настройки'), ('crew', 'Экипаж'), ('aircraft', 'Воздушное судно'), ('service', 'Услуга каталога'), ('airport', 'Аэропорт')], max_length=24)),
                ('entity_id', models.CharField(max_length=40)),
                ('action', models.CharField(help_text='status_changed, vendor_assigned, …', max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ('-ts', '-id'),
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-ts'], name='audit_audit_entity__b94f55_idx'), models.Index(fields=['actor_id', '-ts'], name='audit_audit_actor_i_af32b7_idx')],
            },
        ),
    ]
