# Generated by Django 5.1.6 on 2026-09-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('low_margin_threshold_percent', models.DecimalField(decimal_places=4, default='12.0000', max_digits=6)),
                ('default_markup_percent', models.DecimalField(decimal_places=4, default='15.0000', max_digits=6)),
                ('fx_policy', models.CharField(choices=[('document_date', 'На дату документа'), ('order_date', 'На дату заказа')], default='document_date', help_text='payment_date исключена как нереализуемая, см. ADR-004', max_length=16)),
                ('quote_number_mask', models.CharField(default='SOC-Q-{YYYY}-{NNNN}', max_length=64)),
                ('invoice_number_mask', models.CharField(default='SOC-I-{YYYY}-{NNNN}', max_length=64)),
                ('payable_number_mask', models.CharField(default='SOC-P-{YYYY}-{NNNN}', max_length=64)),
                ('contract_expiry_reminders', models.JSONField(default=list)),
                ('deicing_temp_with_precip_c', models.SmallIntegerField(default=3)),
                ('deicing_temp_always_c', models.SmallIntegerField(default=0)),
                ('pd_retention_months', models.PositiveSmallIntegerField(default=60)),
                ('clock_offset_seconds', models.IntegerField(default=0)),
                ('clock_scale', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
