# Generated by Django 5.1.6 on 2026-09-14 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('is_demo', models.BooleanField(db_index=True, default=False, help_text='Демонстрационная запись, удаляется командой seed_demo --purge')),
                ('data_source', models.CharField(choices=[('synthetic', 'Сгенерировано'), ('user', 'Введено пользователем'), ('imported', 'Импортировано'), ('live', 'Получено из внешней системы')], default='user', help_text='Происхождение данных, см. ADR-010', max_length=16)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('act', 'Акт выполненных работ'), ('receipt', 'Квитанция'), ('invoice', 'Счёт'), ('waybill', 'Накладная'), ('contract', 'Договор'), ('other', 'Прочее')], default='other', max_length=16)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_attach_content_d3cac2_idx')],
            },
        ),
    ]
