# Generated by Django 5.1.6 on 2026-09-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='slot_message_mask',
            field=models.CharField(default='SCR-{YYYY}-{NNNN}', max_length=64),
        ),
    ]
